#!/bin/bash
#install bootchart

function prepare_install()
{
	apt-get update
}

function install_packages()
{
	apt-get install --assume-yes --force-yes "$@"
}

function remove_packages()
{
	apt-get --purge remove --assume-yes --force-yes "$@"
}

prepare_install
install_packages bootchart
