#!/bin/bash
#
# $Id$
#
# NAME:
#	customize_iso -- customize iso image outside of root FS
#
# SYNOPSIS:
#	customize_iso project_dir
#
# DESCRIPTION:
#	This procedure performs additional customization that needs to
#	happen outside of the image of the root file system:
#		- Configuration of the boot environment
#			- isolinux configuration
#			- gfxboot configuration (language/keyboard support!)
#			- propagation of a new kernel/initrd
#			- Simple bootmanager (directory "install" in image)
#		- Configuration of additional resources outside the root FS
#			- Add-Ons (like sample document/music/video files)
#			- More Add-Ons (like OSS for Win / Mac)
#			- Remove Add-Ons
#
# COPYRIGHT:
#	UCK - Ubuntu Customization Kit
#	Copyright (C) 2006-2010 UCK Team
# 
#	UCK is free software: you can redistribute it and/or modify
#	it under the terms of the GNU General Public License as published by
#	the Free Software Foundation, either version 3 of the License, or
#	(at your option) any later version.
#
#	UCK is distributed in the hope that it will be useful,
#	but WITHOUT ANY WARRANTY; without even the implied warranty of
#	MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#	GNU General Public License for more details.
#
#	You should have received a copy of the GNU General Public License
#	along with UCK.  If not, see <http://www.gnu.org/licenses/>.

# Print an error message an exit
failure() { echo "$0: $@" >&2; exit 1; }

# Source environment. Only argument is project directory
if [ -f "$1/customization-scripts/project.uck" ]; then
	. "$1/customization-scripts/project.uck"
else
	failure "Cannot create UCK environment!"
fi

# Can access all of the variables set in project config now:
REMASTER_ROOT="$UCK_PROJECT_DIR/remaster-root"
REMASTER_ISO="$UCK_PROJECT_DIR/remaster-iso"

get_latest_kernel() {
	set -- $(ls "$REMASTER_ROOT"/boot/vmlinuz* 2>/dev/null |
		sed -e "s@$REMASTER_ROOT/boot/@@" |
		tr --  '-.' '\t' |
		sort --key=2 --key=3 --key=4  --key=5 --numeric-sort |
		tail -n1 )
	[ "$1" = "vmlinuz" ] && echo "$REMASTER_ROOT/boot/$1-$2.$3.$4-$5-$6"
}

# Copy kernel and initrd, in case it was updated during customize_root
VMLINUZ=$(get_latest_kernel)
if [ "$VMLINUZ" != "" ]
then
	INITRD="$REMASTER_ROOT"/boot/initrd.img-$(echo `basename $VMLINUZ` | cut -d'-' -f 2-)
	if [ -e "$VMLINUZ" -a -e "$INITRD" ]
	then
		echo "Updating kernel:"
		echo "	kernel=$VMLINUZ"
		echo "	initrd=$INITRD"
		cp -f "$VMLINUZ" "$REMASTER_ISO/casper/vmlinuz"
		cp -f "$INITRD" "$REMASTER_ISO/casper/initrd.gz"
	else
		echo "Not updating kernel as initrd not present"
	fi
fi

# Misc fixup for Karmic
pushd "$REMASTER_ISO"/isolinux >/dev/null

#	-- what used to be a gzipped initrd now is a lzma compressed initrd
if [ -f text.cfg -o -f txt.cfg ]
then
	lzused=`grep initrd.lz text.cfg txt.cfg`
	lzmacmd=`which lzma`
	if [ -n "$lzused" ]
	then
		if [ -n "$lzmacmd" ]
		then
			if [ -f ../casper/initrd.gz ]
			then
				pushd "$REMASTER_ISO"/casper >/dev/null
				echo "Recompressing initrd from gzip to lzma"
				rm -f initrd.lz
				gunzip <initrd.gz | $lzmacmd >initrd.lz
				rm -f initrd.gz
				popd >/dev/null
			fi
		else
			if [ -f ../casper/initrd.gz ]
			then
				echo "lzma command not installed"
				echo "Switching permanently to gzipped initrd"
				sed -i -e 's/initrd\.lz/initrd.gz/g' text.cfg txt.cfg
				rm -f ../casper/initrd.lz
			else
				: do nothing - no initrd.gz
			fi
		fi
	else
		: do nothing - initrd.lz not used
	fi
fi
