#!/bin/bash

###################################################################################
# UCK - Ubuntu Customization Kit                                                  #
# Copyright (C) 2006-2010 UCK Team                                                #
#                                                                                 #
# UCK is free software: you can redistribute it and/or modify                     #
# it under the terms of the GNU General Public License as published by            #
# the Free Software Foundation, either version 3 of the License, or               #
# (at your option) any later version.                                             #
#                                                                                 #
# UCK is distributed in the hope that it will be useful,                          #
# but WITHOUT ANY WARRANTY; without even the implied warranty of                  #
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the                   #
# GNU General Public License for more details.                                    #
#                                                                                 #
# You should have received a copy of the GNU General Public License               #
# along with UCK.  If not, see <http://www.gnu.org/licenses/>.                    #
###################################################################################

REMASTER_HOME="$1"

#############################
# general purpose functions #
#############################

function usage()
{
	echo "Usage: $0 [remaster-dir]"
}

function failure()
{
	echo "$@"
	exit 1
}

#########################
# input parameter check #
#########################

if [ -z "$REMASTER_HOME" ]; then
	REMASTER_HOME=~/tmp
fi

########
# main #
########

. libraries/remaster-live-cd.sh 2>/dev/null || . /usr/lib/uck/remaster-live-cd.sh 2>/dev/null || failure "libraries not found"

echo "Removing win32 files..."
remove_directory "$REMASTER_HOME/remaster-iso/autorun.inf"
remove_directory "$REMASTER_HOME/remaster-iso/bin"
remove_directory "$REMASTER_HOME/remaster-iso/disctree"
remove_directory "$REMASTER_HOME/remaster-iso/pics"
remove_directory "$REMASTER_HOME/remaster-iso/programs"
remove_directory "$REMASTER_HOME/remaster-iso/start.bmp"
remove_directory "$REMASTER_HOME/remaster-iso/start.exe"
remove_directory "$REMASTER_HOME/remaster-iso/start.ini"
remove_directory "$REMASTER_HOME/remaster-iso/ubuntu.ico"
remove_directory "$REMASTER_HOME/remaster-iso/kubuntu.ico"
remove_directory "$REMASTER_HOME/remaster-iso/wubi-cdboot.exe"
remove_directory "$REMASTER_HOME/remaster-iso/wubi.exe"
remove_directory "$REMASTER_HOME/remaster-iso/umenu.exe"
remove_directory "$REMASTER_HOME/remaster-iso/usb-creator.exe"