#!/bin/bash
echo "Using INITRD_REMASTER_DIR=$INITRD_REMASTER_DIR"

MY_CUSTOMIZATION_DIR=`dirname "$0"`

#copy instrumented squashfs module
cp -f "$MY_CUSTOMIZATION_DIR/squashfs.ko" "$INITRD_REMASTER_DIR/lib/modules/2.6.15-23-386/kernel/fs/squashfs/squashfs.ko"
RESULT=$?
if [ $RESULT -ne 0 ]; then
	echo "Failed to copy $MY_CUSTOMIZATION_DIR/squashfs.ko $INITRD_REMASTER_DIR/lib/modules/2.6.15-23-386/kernel/fs/squashfs/squashfs.ko, error=$RESULT"
	exit 4
fi
