#!/bin/bash
echo "Using REMASTER_DIR=$REMASTER_DIR, INITRD_REMASTER_DIR=$INITRD_REMASTER_DIR"

#copy bootchart initramfs script
cp -vf "$REMASTER_DIR/usr/share/initramfs-tools/scripts/init-top/bootchart" "$INITRD_REMASTER_DIR/scripts/init-top/"
RESULT=$?
if [ $RESULT -ne 0 ]; then
	echo "Failed to copy $REMASTER_DIR/usr/share/initramfs-tools/scripts/init-top/bootchart to $INITRD_REMASTER_DIR/scripts/init-top/"
	exit 4
fi
