#!/bin/bash
REMASTER_HOME=$1
ISO_REMASTER_DIR="$REMASTER_HOME/remaster-iso"
REMASTER_DIR="$REMASTER_HOME/remaster-root"
BUILD_DIR=`mktemp -d`

function failure()
{
	echo "$@"
	exit 1
}


pushd "$BUILD_DIR" || failure "Cannot change directory to $BUILD_DIR, error=$?"
apt-get source gfxboot-theme-ubuntu || failure "Failed to fetch gfxboot-theme-ubuntu source, check if you have deb-src line enabled for repository main in /etc/apt/sources.list, error=$?"

cd gfxboot-theme-ubuntu*/

make DEFAULT_LANG=pl || failure "Failed to build gfxboot theme, error=$?"

cp -af boot/* "$ISO_REMASTER_DIR/isolinux/" || failure "Error while copying boot files ( " boot/* " ) to $ISO_REMASTER_DIR/isolinux/, error=$?"

popd

if [ "$BUILD_DIR" = "/" ] ; then
	failure "Trying to remove root dir"
else
	rm -rf "$BUILD_DIR"
fi
