.IX Title "UCK-REMASTER-FINALIZE-ALTERNATE 1"
.TH UCK-REMASTER-FINALIZE-ALTERNATE 1 "2009-02-04" "2.4.5" ""
.\" For nroff, turn off justification.  Always turn off hyphenation; it makes
.\" way too many mistakes in technical documents.
.if n .ad l
.nh
.SH "NAME"
\&\fBuck-remaster-finalize-alternate\fR \- Ubuntu Customization Kit
"alternate" ISO images finalization script
.SH "SYNOPSIS"
.IX Header "SYNOPSIS"
uck-remaster-finalize-alternate gpg-key-id [remaster-dir]
.SH "DESCRIPTION"
.IX Header "DESCRIPTION"
\&\fBuck-remaster-finalize-alternate generates new keyring package with your
gpg signature, Release files and Indexes. This script is the last one to
call when working on an "alternate" ISO image.
.SH "AUTHOR"
.IX Header "AUTHOR"
\fBUbuntu Customization Kit\fR has been written by Fabrizio Balliano \
<fabrizio.balliano@crealabs.it> and Krzysztof Lichota <krzysiek@lichota.net>
.PP
This manual was provided by Fabrizio Balliano <fabrizio.balliano@crealabs.it>
and Alessio Treglia <quadrispro@ubuntu.com>.
.PP
Source code for the \fBUbuntu Customization Kit\fR is available at
http://uck.sourceforge.net
.PP
Bugs can be reported at https://bugs.launchpad.net/uck/
