#!/bin/bash

###################################################################################
# UCK - Ubuntu Customization Kit                                                  #
# Copyright (C) 2006-2010 UCK Team                                                #
#                                                                                 #
# UCK is free software: you can redistribute it and/or modify                     #
# it under the terms of the GNU General Public License as published by            #
# the Free Software Foundation, either version 3 of the License, or               #
# (at your option) any later version.                                             #
#                                                                                 #
# UCK is distributed in the hope that it will be useful,                          #
# but WITHOUT ANY WARRANTY; without even the implied warranty of                  #
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the                   #
# GNU General Public License for more details.                                    #
#                                                                                 #
# You should have received a copy of the GNU General Public License               #
# along with UCK.  If not, see <http://www.gnu.org/licenses/>.                    #
###################################################################################

REMASTER_HOME=$1
REMASTER_DIR="$REMASTER_HOME/remaster-root"
INITRD_REMASTER_DIR="$REMASTER_HOME/remaster-initrd"

echo "Using INITRD_REMASTER_DIR=$INITRD_REMASTER_DIR"

INIT_TOP_FILE="$INITRD_REMASTER_DIR/scripts/init-top/enable_vm_block_dump"

echo 'grep -q "vm_block_dump=disable" /proc/cmdline && exit 0' > "$INIT_TOP_FILE"
echo 'echo -n 1 >/proc/sys/vm/block_dump' >> "$INIT_TOP_FILE"
RESULT=$?
if [ $RESULT -ne 0 ]; then
	echo "Failed to create $INIT_TOP_FILE, error=$RESULT"
	exit 2
fi

chmod +x "$INIT_TOP_FILE"
RESULT=$?
if [ $RESULT -ne 0 ]; then
	echo "Failed to make $INIT_TOP_FILE executable, error=$RESULT"
	exit 3
fi
