#!/bin/bash

###################################################################################
# UCK - Ubuntu Customization Kit                                                  #
# Copyright (C) 2006  UCK Team                                                    #
#                                                                                 #
# This program is free software; you can redistribute it and/or                   #
# modify it under the terms of the GNU General Public License                     #
# as published by the Free Software Foundation; version 2                  #
# of the License.                                                                 #
#                                                                                 #
# This program is distributed in the hope that it will be useful,                 #
# but WITHOUT ANY WARRANTY; without even the implied warranty of                  #
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the                   #
# GNU General Public License for more details.                                    #
#                                                                                 #
# You should have received a copy of the GNU General Public License               #
# along with this program; if not, write to the Free Software                     #
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA. #
###################################################################################

ISO_IMAGE="$1"
CUSTOMIZE_DIR="$2"
ISO_MOUNT_DIR=~/tmp/iso-source2
REMASTER_DIR=~/tmp/remaster-root
ISO_REMASTER_DIR=~/tmp/remaster-iso
INITRD_REMASTER_DIR=~/tmp/remaster-initrd
SQUASHFS_IMAGE="$ISO_REMASTER_DIR/casper/filesystem.squashfs"
SQUASHFS_MOUNT_DIR=~/tmp/squashfs-source
REMASTER_CUSTOMIZE_RELATIVE_DIR="tmp/customize-dir"
REMASTER_CUSTOMIZE_DIR="$REMASTER_DIR/$REMASTER_CUSTOMIZE_RELATIVE_DIR"
CUSTOMIZATION_SCRIPT="$REMASTER_CUSTOMIZE_RELATIVE_DIR/customize"
#Name of directory where packages downloaded by apt are kept across build runs
#Allows saving bandwidth for downloading all updates
#Important: no "/" at the end of directory name!
APT_CACHE_SAVE_DIR=~/tmp/remaster-apt-cache
NEW_FILES_DIR=~/tmp/remaster-new-files

echo "Starting CD remastering on " `date`
echo "Customization dir=$CUSTOMIZE_DIR"

export LC_ALL=C

. libraries/remaster-live-cd.sh

trap unmount_all EXIT
trap unmount_all SIGINT

if [ -z "$ISO_IMAGE" ]; then
	usage
	exit 1
fi

if [ -z "$CUSTOMIZE_DIR" ]; then
	usage
	exit 1
fi

CUSTOMIZE_ROOTFS="no"
CUSTOMIZE_INITRD="no"
CUSTOMIZE_ISO="no"
KEEP_PREVIOUS_ISO_EXTRACTION="no"
KEEP_PREVIOUS_REMASTER_DIR="no"

if [ -e "$CUSTOMIZE_DIR/customize" ]; then
	CUSTOMIZE_ROOTFS="yes"
fi

if [ -e "$CUSTOMIZE_DIR/customize_initrd" ]; then
	CUSTOMIZE_INITRD="yes"
fi

if [ -e "$CUSTOMIZE_DIR/customize_iso" ]; then
	CUSTOMIZE_ISO="yes"
fi

if [ -e "$CUSTOMIZE_DIR/keep_iso_extraction" ] ; then
	KEEP_PREVIOUS_ISO_EXTRACTION="yes"
fi

if [ "$KEEP_PREVIOUS_ISO_EXTRACTION" = "no" ] || [ ! -e "$ISO_REMASTER_DIR" ] ; then
	mount_iso
	unpack_iso
	unmount_iso
fi

export ISO_REMASTER_DIR

if [ "$CUSTOMIZE_ROOTFS" = "yes" ] ; then
	if [ -e "$CUSTOMIZE_DIR/keep_rootfs_extraction" ] ; then
		KEEP_PREVIOUS_REMASTER_DIR="yes"
	fi

	if [ "$KEEP_PREVIOUS_REMASTER_DIR" = "no" ] || [ ! -e "$REMASTER_DIR" ] ; then
		unpack_rootfs
	fi
	export REMASTER_DIR
fi

if [ "$CUSTOMIZE_INITRD" = "yes" ] ; then
	unpack_initrd
	export INITRD_REMASTER_DIR
fi

if [ "$CUSTOMIZE_ROOTFS" = "yes" ] ; then
	prepare_rootfs_for_net_update
	run_rootfs_chroot_customization
fi

if [ "$CUSTOMIZE_INITRD" = "yes" ] ; then
	customize_initrd
fi

if [ "$CUSTOMIZE_ISO" = "yes" ] ; then
	customize_iso
fi

if [ "$MANUAL_CUSTOMIZATION_PAUSE" = "yes" ] ; then
	echo "Pausing for manual customization, press Enter when finished..."
	read DUMMY
fi

if [ "$CUSTOMIZE_ROOTFS" = "yes" ] ; then
	save_apt_cache
	clean_rootfs
fi

prepare_new_files_directories

if [ "$CUSTOMIZE_INITRD" = "yes" ] ; then
	pack_initrd
fi

if [ "$CUSTOMIZE_ROOTFS" = "yes" ] ; then
	pack_rootfs
fi


remove_remaster_initrd
export -n INITRD_REMASTER_DIR

pack_isofs
unmount_all
#reset EXIT handler from unmount_all to none
trap - EXIT

if [ "$CUSTOMIZE_ROOTFS" = "yes" ] ; then
	if [ "$KEEP_PREVIOUS_REMASTER_DIR" = "no" ] ; then
		remove_remaster_dir
	fi
	export -n REMASTER_DIR
fi

if [ "$KEEP_PREVIOUS_ISO_EXTRACTION" = "no" ] ; then
	remove_iso_remaster_dir
fi

export -n ISO_REMASTER_DIR

echo "Generation completed SUCCESSFULLY, find your ISO in $NEW_FILES_DIR"


exit 0
