#!/bin/bash

###################################################################################
# UCK - Ubuntu Customization Kit                                                  #
# Copyright (C) 2006  UCK Team                                                    #
#                                                                                 #
# This program is free software; you can redistribute it and/or                   #
# modify it under the terms of the GNU General Public License                     #
# as published by the Free Software Foundation; version 2                         #
# of the License.                                                                 #
#                                                                                 #
# This program is distributed in the hope that it will be useful,                 #
# but WITHOUT ANY WARRANTY; without even the implied warranty of                  #
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the                   #
# GNU General Public License for more details.                                    #
#                                                                                 #
# You should have received a copy of the GNU General Public License               #
# along with this program; if not, write to the Free Software                     #
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA. #
###################################################################################

REMASTER_HOME="$1"

#############################
# general purpose functions #
#############################

function usage()
{
	echo "Usage: $0 [remaster-dir]"
}

function failure()
{
	echo "$@"
	exit 1
}

#########################
# input parameter check #
#########################

if [ -z "$REMASTER_HOME" ]; then
	REMASTER_HOME=~/tmp
fi

########
# main #
########

. libraries/remaster-live-cd.sh 2>/dev/null || . /usr/lib/uck/remaster-live-cd.sh 2>/dev/null || failure "libraries not found"

INITRD_REMASTER_DIR="$REMASTER_HOME/remaster-initrd"
ISO_REMASTER_DIR="$REMASTER_HOME/remaster-iso"
REMASTER_DIR="$REMASTER_HOME/remaster-root"

if [ ! -e "$REMASTER_HOME/customization-scripts/keep_initrd_extraction" ] ; then
	remove_remaster_initrd
fi

if [ ! -e "$REMASTER_HOME/customization-scripts/keep_rootfs_extraction" ] ; then
	remove_remaster_dir
fi

if [ ! -e "$REMASTER_HOME/customization-scripts/keep_iso_extraction" ] ; then
	remove_iso_remaster_dir
fi