#!/bin/bash
echo "Using INITRD_REMASTER_DIR=$INITRD_REMASTER_DIR"

MY_CUSTOMIZATION_DIR=`dirname "$0"`

#copy instrumented squashfs module
cp -f "$MY_CUSTOMIZATION_DIR/squashfs.ko" "$INITRD_REMASTER_DIR/lib/modules/2.6.15-23-386/kernel/fs/squashfs/squashfs.ko"
RESULT=$?
if [ $RESULT -ne 0 ]; then
	echo "Failed to copy $MY_CUSTOMIZATION_DIR/squashfs.ko $INITRD_REMASTER_DIR/lib/modules/2.6.15-23-386/kernel/fs/squashfs/squashfs.ko, error=$RESULT"
	exit 4
fi

INIT_TOP_FILE="$INITRD_REMASTER_DIR/scripts/init-top/enable_vm_block_dump"

echo 'grep -q "vm_block_dump=disable" /proc/cmdline && exit 0' > "$INIT_TOP_FILE"
echo 'echo -n 1 >/proc/sys/vm/block_dump' >> "$INIT_TOP_FILE"
RESULT=$?
if [ $RESULT -ne 0 ]; then
	echo "Failed to create $INIT_TOP_FILE, error=$RESULT"
	exit 2
fi

chmod +x "$INIT_TOP_FILE"
RESULT=$?
if [ $RESULT -ne 0 ]; then
	echo "Failed to make $INIT_TOP_FILE executable, error=$RESULT"
	exit 3
fi
