.IX Title "UCK-REMASTER 1"
.TH UCK-REMASTER 1 "2009-02-04" "2.0.11" ""
.\" For nroff, turn off justification.  Always turn off hyphenation; it makes
.\" way too many mistakes in technical documents.
.if n .ad l
.nh
.SH "NAME"
\&\fBuck-remaster\fR \- Ubuntu Customization Kit main remastering backend script
.SH "SYNOPSIS"
.IX Header "SYNOPSIS"
uck-remaster iso-file.iso [customization-scripts-dir]
.SH "DESCRIPTION"
.IX Header "DESCRIPTION"
\&\fBuck-remaster takes an Ubuntu ISO image and a "remastering scripts diredtory"
and do the whole process of generating the customized ISO automatically.
.SH "AUTHOR"
.IX Header "AUTHOR"
\fBUbuntu Customization Kit\fR has been written by Fabrizio Balliano \
<fabrizio.balliano@crealabs.it> and Krzysztof Lichota <krzysiek@lichota.net>
.PP
This manual was provided by Fabrizio Balliano <fabrizio.balliano@crealabs.it>
and Alessio Treglia <quadrispro@ubuntu.com>.
