.IX Title "UCK-REMASTER-UMOUNT 1"
.TH UCK-REMASTER-UMOUNT 1 "2010-05-30" "2.4.5" ""
.\" For nroff, turn off justification.  Always turn off hyphenation; it makes
.\" way too many mistakes in technical documents.
.if n .ad l
.nh
.SH "NAME"
\&\fBuck-remaster-umount\fR \- Ubuntu Customization Kit image
unmounting script
.SH "SYNOPSIS"
.IX Header "SYNOPSIS"
uck-remaster-umount [remaster-dir]
.SH "DESCRIPTION"
.IX Header "DESCRIPTION"
\&\fBuck-remaster-mount\fR undoes the mounts created by \fBuck-remaster-mount\fR.
If the second argument is not specified, it defaults to ~/tmp.
.SH "AUTHOR"
.IX Header "AUTHOR"
\fBUbuntu Customization Kit\fR has been written by Fabrizio Balliano \
<fabrizio.balliano@crealabs.it> and Krzysztof Lichota <krzysiek@lichota.net>
.PP
This manual was provided by Wolf Geldmacher <wolf@womaro.ch>.
.PP
Source code for the \fBUbuntu Customization Kit\fR is available at
http://uck.sourceforge.net
.PP
Bugs can be reported at https://bugs.launchpad.net/uck/
