.IX Title "UCK-REMASTER-CLEAN-ALL 1"
.TH UCK-REMASTER-CLEAN-ALL 1 "2009-02-04" "2.4.5" ""
.\" For nroff, turn off justification.  Always turn off hyphenation; it makes
.\" way too many mistakes in technical documents.
.if n .ad l
.nh
.SH "NAME"
\&\fBuck-remaster-clean-all\fR \- Ubuntu Customization Kit cleaning helper script
.SH "SYNOPSIS"
.IX Header "SYNOPSIS"
uck-remaster-clean [remaster-dir]
.SH "DESCRIPTION"
.IX Header "DESCRIPTION"
\&\fBuck-remaster-clean-all removes all directories created in the remastering process.
.SH "AUTHOR"
.IX Header "AUTHOR"
\fBUbuntu Customization Kit\fR has been written by Fabrizio Balliano \
<fabrizio.balliano@crealabs.it> and Krzysztof Lichota <krzysiek@lichota.net>
.PP
This manual was provided by Fabrizio Balliano <fabrizio.balliano@crealabs.it>
and Alessio Treglia <quadrispro@ubuntu.com>.
.PP
Source code for the \fBUbuntu Customization Kit\fR is available at
http://uck.sourceforge.net
.PP
Bugs can be reported at https://bugs.launchpad.net/uck/
