.IX Title "UCK-REMASTER-CHROOT-ROOTFS 1"
.TH UCK-REMASTER-CHROOT-ROOTFS 1 "2009-01-30" "2.0.7" ""
.\" For nroff, turn off justification.  Always turn off hyphenation; it makes
.\" way too many mistakes in technical documents.
.if n .ad l
.nh
.SH "NAME"
\&\fBuck-remaster-chroot-rootfs\fR \- Ubuntu Customization Kit chroot
helper script
.SH "SYNOPSIS"
.IX Header "SYNOPSIS"
uck-remaster-chroot-rootfs [what-to-execute] [remaster-dir]
.SH "DESCRIPTION"
.IX Header "DESCRIPTION"
\&\fBuck-remaster-chroot-rootfs executes the script passed as the first param
(/bin/bash if empty) inside the rootfs chrooted environment.
.SH "AUTHOR"
.IX Header "AUTHOR"
\fBUbuntu Customization Kit\fR has been written by Fabrizio Balliano \
<fabrizio.balliano@crealabs.it> and Krzysztof Lichota <krzysiek@lichota.net>
.PP
This manual was provided by Fabrizio Balliano <fabrizio.balliano@crealabs.it>
and Alessio Treglia <quadrispro@ubuntu.com>.
