#!/bin/bash
#install polish language packs

function prepare_install()
{
	apt-get update
}

function install_packages()
{
	apt-get install --assume-yes --force-yes "$@"
}

function remove_packages()
{
	apt-get --purge remove --assume-yes --force-yes "$@"
}

prepare_install
echo "Installing language pack..."
install_packages language-pack-pl language-support-pl language-pack-kde-pl myspell-dictionary-pl openoffice.org-hyphenation-pl   openoffice.org-thesaurus-pl openoffice.org-help-pl
#REMOVED_PACKAGES="language-pack-en language-support-en language-pack-kde-en language-pack-kde-en-base \
#	wamerican wbritish mozilla-firefox-locale-en-gb myspell-en-gb myspell-en-us \
#	aspell-en \"
#	openoffice.org-thesaurus-en-us openoffice.org-l10n-en-gb openoffice.org-l10n-en-za"

#REMOVED_PACKAGES=`dpkg-query --show | cut -f1 | grep '^language-'`

#Remove language packs apart from Polish and English.
echo "Removing packages..."
#NOTE: we first install language pack, then remove others as installing language pack might pull packages 
#which were not previously present
echo "Removing unnecessary language packages..."
LANGPACKS_CONCATENATED=pl
REMOVED_PACKAGES=`dpkg-query --show | cut -f1 | grep -E '^(language-pack|language-support)' | grep -v -E "[-]($LANGPACKS_CONCATENATED)\>"`
remove_packages $REMOVED_PACKAGES || failure "Removing packages failed, error=$?"

echo "Done"
#Removing openoffice.org-l10n-en-us uninstalls Openoffice
