#!/bin/bash

###################################################################################
# UCK - Ubuntu Customization Kit                                                  #
# Copyright (C) 2006-2007 UCK Team                                                #
#                                                                                 #
# This program is free software; you can redistribute it and/or                   #
# modify it under the terms of the GNU General Public License                     #
# as published by the Free Software Foundation; version 2                         #
# of the License.                                                                 #
#                                                                                 #
# This program is distributed in the hope that it will be useful,                 #
# but WITHOUT ANY WARRANTY; without even the implied warranty of                  #
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the                   #
# GNU General Public License for more details.                                    #
#                                                                                 #
# You should have received a copy of the GNU General Public License               #
# along with this program; if not, write to the Free Software                     #
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA. #
###################################################################################

#############################
# general purpose functions #
#############################

function usage()
{
	echo "Usage: $0 [iso-file-name.iso] [remaster-dir] [-g|--generate-md5] [-a|--arch=x86,x86_64,ia64,ppc]"
}

function failure()
{
	echo "$@"
	exit 1
}

#########################
# input parameter check #
#########################

ARCH="x86"
GENERATE_MD5_FOR_NEW_ISO=0

INPUT_PARAMS=`getopt -u -o ga: -l generate-md5,arch: -n "$0" -- "$@"`

if [ $? != 0 ] ; then
	exit 1
fi

set -- $INPUT_PARAMS
for i
do
  case "$i" in
        -g|--generate-md5) shift;GENERATE_MD5_FOR_NEW_ISO=1;;
        -a|--arch) shift; ARCH=$1; shift;;
        --) shift;;
  esac
done

NEW_ISO_FILE_NAME=$1
if [ -z "$NEW_ISO_FILE_NAME" ]; then
	NEW_ISO_FILE_NAME="livecd.iso"
fi

REMASTER_HOME=$2
if [ -z "$2" ]; then
	REMASTER_HOME=~/tmp
fi

if [ "$ARCH" != "x86" ] && [ "$ARCH" != "x86_64" ] && [ "$ARCH" != "ia64" ] && [ "$ARCH" != "ppc" ]; then
	failure "Chosen architecture is not valid (x86, x86_64, ia64, ppc)"
fi

########
# main #
########

. libraries/remaster-live-cd.sh 2>/dev/null || . /usr/lib/uck/remaster-live-cd.sh 2>/dev/null || failure "libraries not found"

NEW_FILES_DIR="$REMASTER_HOME/remaster-new-files"
INITRD_REMASTER_DIR="$REMASTER_HOME/remaster-initrd"
ISO_REMASTER_DIR="$REMASTER_HOME/remaster-iso"
REMASTER_DIR="$REMASTER_HOME/remaster-root"
CUSTOMIZE_DIR="$REMASTER_HOME/customization-scripts"

if [ ! -e "$ISO_REMASTER_DIR" ]; then
	failure "ISO remastering directory does not exists"
fi

prepare_new_files_directories
pack_iso "$ARCH"

if [ $GENERATE_MD5_FOR_NEW_ISO = 1 ]; then
	generate_md5_for_new_iso
fi