#!/bin/bash

###################################################################################
# UCK - Ubuntu Customization Kit                                                  #
# Copyright (C) 2006-2008 UCK Team                                                #
#                                                                                 #
# This program is free software: you can redistribute it and/or modify            #
# it under the terms of the GNU General Public License as published by            #
# the Free Software Foundation, version 3 of the License.                         #
#                                                                                 #
# This program is distributed in the hope that it will be useful,                 #
# but WITHOUT ANY WARRANTY; without even the implied warranty of                  #
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the                   #
# GNU General Public License for more details.                                    #
#                                                                                 #
# You should have received a copy of the GNU General Public License               #
# along with this program.  If not, see <http://www.gnu.org/licenses/>.           #
###################################################################################

ISO_IMAGE="$1"
CUSTOMIZE_DIR="$2"
REMASTER_HOME=~/tmp

##################
# some functions #
##################

function usage()
{
	echo "Usage: $0 iso-file.iso [customization-scripts-dir]"
}

function check_exit_code()
{
	RESULT=$?
	if [ "$RESULT" -ne 0 ]; then
		exit "$RESULT"
	fi
}

function check_if_user_is_root()
{
	if [ `id -un` != "root" ]; then
		echo "You need root privileges"
		exit 2
	fi
}

#########################
# input parameter check #
#########################

if [ -z "$ISO_IMAGE" ]; then
	usage
	exit 1
fi

if [ -z "$CUSTOMIZE_DIR" ]; then
	CUSTOMIZE_DIR="$REMASTER_HOME/customization-scripts"
fi

########
# main #
########

check_if_user_is_root

if [ -e libraries/remaster-live-cd.sh ]; then
	SCRIPTS_DIR=`dirname "$0"`
	VERSION=`cat VERSION`
else
	SCRIPTS_DIR=/usr/bin
	VERSION=`cat /usr/lib/uck/VERSION`
fi

echo "Ubuntu Customization Kit $VERSION"
echo "Starting CD remastering on " `date`
echo "Customization dir=$CUSTOMIZE_DIR"

CUSTOMIZE_ROOTFS="no"
CUSTOMIZE_INITRD="no"
CUSTOMIZE_ISO="no"
REMOVE_WIN32_FILES=`cat "$CUSTOMIZE_DIR/remove_win32_files"`
CLEAN_DESKTOP_MANIFEST="no"

if [ -e "$CUSTOMIZE_DIR/customize" ]; then
	CUSTOMIZE_ROOTFS="yes"
fi

if [ -e "$CUSTOMIZE_DIR/customize_initrd" ]; then
	CUSTOMIZE_INITRD="yes"
fi

if [ -e "$CUSTOMIZE_DIR/customize_iso" ]; then
	CUSTOMIZE_ISO="yes"
fi

if [ -e "$CUSTOMIZE_DIR/clean_desktop_manifest" ]; then
	CLEAN_DESKTOP_MANIFEST="yes"
fi

$SCRIPTS_DIR/uck-remaster-clean "$REMASTER_HOME"
check_exit_code

#############
# unpacking #
#############

if [ "$CUSTOMIZE_ISO" = "yes" ] ; then
	$SCRIPTS_DIR/uck-remaster-unpack-iso "$ISO_IMAGE" "$REMASTER_HOME"
	check_exit_code
fi

if [ "$CUSTOMIZE_INITRD" = "yes" ] ; then
	$SCRIPTS_DIR/uck-remaster-unpack-initrd "$REMASTER_HOME"
	check_exit_code
fi

if [ "$CUSTOMIZE_ISO" = "yes" ] && [ "$CUSTOMIZE_ROOTFS" = "yes" ] ; then
	$SCRIPTS_DIR/uck-remaster-unpack-rootfs "$REMASTER_HOME"
	check_exit_code
fi

###############
# customizing #
###############

if [ "$REMOVE_WIN32_FILES" = "yes" ]; then
	"$SCRIPTS_DIR/uck-remaster-remove-win32-files" "$REMASTER_HOME"
	check_exit_code
fi

if [ "$CUSTOMIZE_INITRD" = "yes" ] ; then
	echo "Running initrd customization script $CUSTOMIZE_DIR/customize_initrd..."
	"$CUSTOMIZE_DIR/customize_initrd" "$REMASTER_HOME"
	check_exit_code
	echo "Initrd customization script finished"
fi

if [ "$CUSTOMIZE_ISO" = "yes" ] && [ "$CUSTOMIZE_ROOTFS" = "yes" ] ; then
	$SCRIPTS_DIR/uck-remaster-chroot-rootfs "/tmp/customization-scripts/customize" "$REMASTER_HOME"
	check_exit_code
fi

if [ "$CUSTOMIZE_ISO" = "yes" ] ; then
	echo "Running ISO customization script $CUSTOMIZE_DIR/customize_iso..."
	"$CUSTOMIZE_DIR/customize_iso" "$REMASTER_HOME"
	check_exit_code
	echo "ISO customization script finished"
fi

if [ "$MANUAL_CUSTOMIZATION_PAUSE" = "yes" ] ; then
	echo "Pausing for manual customization, press Enter when finished..."
	read DUMMY
fi

###########
# packing #
###########

if [ "$CUSTOMIZE_INITRD" = "yes" ] ; then
	$SCRIPTS_DIR/uck-remaster-pack-initrd "$REMASTER_HOME"
	check_exit_code
fi

if [ "$CUSTOMIZE_ROOTFS" = "yes" ] ; then
	if [ "$CLEAN_DESKTOP_MANIFEST" = "yes" ]; then
		$SCRIPTS_DIR/uck-remaster-pack-rootfs -c "$REMASTER_HOME"
	else
		$SCRIPTS_DIR/uck-remaster-pack-rootfs "$REMASTER_HOME"
	fi
	check_exit_code
fi

$SCRIPTS_DIR/uck-remaster-pack-iso "livecd.iso" "$REMASTER_HOME"
check_exit_code

#############
# finishing #
#############

$SCRIPTS_DIR/uck-remaster-clean "$REMASTER_HOME"
check_exit_code

echo "Generation completed SUCCESSFULLY, find your ISO in $REMASTER_HOME/remaster-new-files"
exit 0