#!/bin/bash

###################################################################################
# UCK - Ubuntu Customization Kit                                                  #
# Copyright (C) 2006-2010 UCK Team                                                #
#                                                                                 #
# UCK is free software: you can redistribute it and/or modify                     #
# it under the terms of the GNU General Public License as published by            #
# the Free Software Foundation, either version 3 of the License, or               #
# (at your option) any later version.                                             #
#                                                                                 #
# UCK is distributed in the hope that it will be useful,                          #
# but WITHOUT ANY WARRANTY; without even the implied warranty of                  #
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the                   #
# GNU General Public License for more details.                                    #
#                                                                                 #
# You should have received a copy of the GNU General Public License               #
# along with UCK.  If not, see <http://www.gnu.org/licenses/>.                    #
###################################################################################

#############################
# general purpose functions #
#############################

function usage()
{
	echo "Usage: $0 [remaster-dir] [-c|--clean-desktop-manifest]"
}

function failure()
{
	echo "$@"
	exit 1
}

#########################
# input parameter check #
#########################

CLEAN_DESKTOP_MANIFEST=0

INPUT_PARAMS=`getopt -u -o c -l clean-desktop-manifest -n "$0" -- "$@"`

if [ $? != 0 ] ; then
	exit 1
fi

set -- $INPUT_PARAMS
for i
do
  case "$i" in
        -c|--clean-desktop-manifest) shift;CLEAN_DESKTOP_MANIFEST=1;;
        --) shift;;
  esac
done

REMASTER_HOME="$1"
if [ -z "$REMASTER_HOME" ]; then
	REMASTER_HOME=~/tmp
fi

########
# main #
########

. libraries/remaster-live-cd.sh 2>/dev/null || . /usr/lib/uck/remaster-live-cd.sh 2>/dev/null || failure "libraries not found"

ISO_REMASTER_DIR="$REMASTER_HOME/remaster-iso"
REMASTER_DIR="$REMASTER_HOME/remaster-root"

pack_rootfs