#!/bin/bash
#
# $Id: customize_iso,v 2.1 2010-02-22 09:19:02 wjg Exp $
#
# NAME:
#	customize_iso -- customize iso image outside of root FS
#
# SYNOPSIS:
#	customize_iso project_dir
#
# DESCRIPTION:
#	This procedure performs additional customization that needs to
#	happen outside of the image of the root file system:
#		- Configuration of the boot environment
#			- isolinux configuration
#			- gfxboot configuration (language/keyboard support!)
#			- propagation of a new kernel/initrd
#			- Simple bootmanager (directory "install" in image)
#		- Configuration of additional resources outside the root FS
#			- Add-Ons (like sample document/music/video files)
#			- More Add-Ons (like OSS for Win / Mac)
#			- Remove Add-Ons
#
# NOTES:
#	Execution of the procedure may require Internet access to download
#	the source of the latest version gfxboot-theme-ubuntu via wget.
#
#	If a local copy of gfxboot-theme-ubuntu is available in the remaster
#	home, it will be used instead of a (possibly updated) download.
#
# COPYRIGHT:
#	UCK - Ubuntu Customization Kit
#	Copyright (C) 2006-2010 UCK Team
# 
#	UCK is free software: you can redistribute it and/or modify
#	it under the terms of the GNU General Public License as published by
#	the Free Software Foundation, either version 3 of the License, or
#	(at your option) any later version.
#
#	UCK is distributed in the hope that it will be useful,
#	but WITHOUT ANY WARRANTY; without even the implied warranty of
#	MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#	GNU General Public License for more details.
#
#	You should have received a copy of the GNU General Public License
#	along with UCK.  If not, see <http://www.gnu.org/licenses/>.

# Print an error message an exit
failure() { echo "$0: $@" >&2; exit 1; }

# Source environment. Only argument is project directory
if [ -f "$1/customization-scripts/project.uck" ]; then
	. "$1/customization-scripts/project.uck"
else
	failure "Cannot create UCK environment!"
fi

# Can access all of the variables set in project config now:
PROJECT_DIR="$UCK_PROJECT_DIR"
REMASTER_ROOT="$UCK_PROJECT_DIR/remaster-root"
REMASTER_ISO="$UCK_PROJECT_DIR/remaster-iso"
SCRIPT_DIR="$UCK_PROJECT_DIR/customization-scripts"

# Default version does nothing
exit 0
