#!/bin/bash
REMASTER_HOME=$1
REMASTER_DIR="$REMASTER_HOME/remaster-root"
INITRD_REMASTER_DIR="$REMASTER_HOME/remaster-initrd"

echo "Using INITRD_REMASTER_DIR=$INITRD_REMASTER_DIR"

#copy bootchart initramfs script
cp -f "/usr/share/initramfs-tools/scripts/init-top/bootchart" "$INITRD_REMASTER_DIR/scripts/init-top/"
RESULT=$?
if [ $RESULT -ne 0 ]; then
	echo "Failed to copy /usr/share/initramfs-tools/scripts/init-top/bootchart to $INITRD_REMASTER_DIR/scripts/init-top/"
	exit 4
fi
